### ISSUE TITLE
How to loop the animation? Add controls?

### ISSUE THREAD

**Issue by pplonski** [vizzuhq/ipyvizzu#104]
This is a great library! Exactly the lib that I was looking for! Thank you! :1st_place_medal: 

How to run the animation in the loop? Can I add controls for animation (stop, play)?

I'm working on a [framework](https://github.com/mljar/mercury) for converting Jupyter Notebooks to interactive web apps. Would love to use vizzu in demos. I will let you know, thanks!

**Comment by petervidos** [comment]
Hey Piotr,
Thanks for the kind words!😍
Here is an example where the animation is in a loop, not sure that this is what you need though: https://github.com/vizzuhq/ipyvizzu/blob/main/docs/examples/stories/music-history/music-history.ipynb

The animation control API of Vizzu is not yet supported through ipyvizzu, but you can access it via raw javascript: https://lib.vizzuhq.com/0.4/#chapter-0.15

We'd be happy to discuss what you want to use ipyvizzu for in Mercury in more detail.

**Comment by veghdev** [comment]
@pplonski We have created a presentation extension for ipyvizzu called [ipyvizzu-story](https://github.com/vizzuhq/ipyvizzu-story). This allows you to control the chart without writing javascript code.

**Comment by pplonski** [comment]
`ipyvizzu-story` looks amazing!
