### ISSUE TITLE
Doesn't work in databrick notebook

### ISSUE THREAD

**Issue by petervidos** [vizzuhq/ipyvizzu#111]
Example: https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/2804273370363137/1363672035823085/1736236844723331/latest.html

**Comment by simzer** [comment]
@petervidos Please check again with new 0.8.1 release, using this setting:
```python
chart = Chart(display="manual") 
# chart.animate(...)
# ...
chart.show()
```

**Comment by veghdev** [comment]
#142
