### ISSUE TITLE
js_separation branch: chart does not move in generated htmls

### ISSUE THREAD

**Issue by veghdev** [vizzuhq/ipyvizzu#112]
With the new separated js class in the generated htmls the chart displayed after the first cell, and not moved (display="actual")
Even with manually saved ipynb output, even if nbconvert generated it.

Example:

cd tools/html-generator

with execute flag *if output not created and saved manually:
../../.venv/bin/jupyter nbconvert --Exporter.preprocessors=preprocessor.NbPreprocessor --to html --execute ../../docs/tutorial/sorting.ipynb

without execute flag *if output created and saved manually:
../../.venv/bin/jupyter nbconvert --Exporter.preprocessors=preprocessor.NbPreprocessor --to html ../../docs/tutorial/sorting.ipynb

**Comment by simzer** [comment]
This seems to be a bug in nbconvert. I have reported this issue: https://github.com/jupyter/nbconvert/issues/1759

Meanwhile, we should switch back to generating `div`s with a unique id for ourselves for the time being.
