### ISSUE TITLE
Doc site - navigation for example pages

### ISSUE THREAD

**Issue by petervidos** [vizzuhq/ipyvizzu#131]
needs a back button.

**Comment by Siddhant-K-code** [comment]
Do you mean, the back button to GitHub Repository Page from [Examples page](https://vizzuhq.github.io/ipyvizzu/examples/examples.html)?

We can have a header with GitHub Logo, Repo Stars Count & It's URL. Which sends back the user to this repository.

**Comment by veghdev** [comment]
I think we should put a navigation link at the end of examples.md and each example to allow the user to navigate back to the main page of the documentation site (https://vizzuhq.github.io/ipyvizzu/index.html#tutorial) and to the examples page (https://vizzuhq.github.io/ipyvizzu/examples/examples.html). As used on each page of the tutorial (for example: https://vizzuhq.github.io/ipyvizzu/tutorial/geometry.html)

examples and examples.md are generated by tools/example-generator, so the modification needs to do here.

The other problem, github generates this text "This site is open source. Improve this." to the end of the file, which is incorrect. examples.md is generated, so any direct modification will be lost.

**Comment by veghdev** [comment]
I added a Data Story to the Examples:
https://vizzuhq.github.io/ipyvizzu/examples/examples.html

I placed an example navigation links at the end of the music formats example (data stories example is not currently generated).
