### ISSUE TITLE
DATASET used in ipyvizzu examples.

### ISSUE THREAD

**Issue by dove88** [vizzuhq/ipyvizzu#132]
Hello, may I ask, where can I get datasets used in examples charts?

**Comment by veghdev** [comment]
@dove88 Thank you for your interest.
In the [static charts](https://vizzuhq.github.io/ipyvizzu/examples/examples.html#static-charts) and [animated charts](https://vizzuhq.github.io/ipyvizzu/examples/examples.html#static-charts) we use these [csv files](https://github.com/vizzuhq/ipyvizzu/tree/gh-pages/docs/data).

The data stories csv files are in the story folder. For example [music format](https://github.com/vizzuhq/ipyvizzu/tree/gh-pages/docs/examples/stories/musicformats).

In the tutorial we use this [json file](https://github.com/vizzuhq/ipyvizzu/blob/gh-pages/docs/tutorial/music_data.json), as it has been mentioned in this [chapter](https://vizzuhq.github.io/ipyvizzu/tutorial/data.html#json)

If you have any other question please let us know.

**Comment by veghdev** [comment]
csv files of the static and animated examples can not be found in the main branch because we get these from [vizzu-lib repo](https://github.com/vizzuhq/vizzu-lib) and generate with tools/example-generator/run.sh in the doc.yml workflow.

**Comment by dove88** [comment]
Thank you very much
