### ISSUE TITLE
Make it easy to use Ipyvizzu with Panel

### ISSUE THREAD

**Issue by MarcSkovMadsen** [vizzuhq/ipyvizzu#133]
Panel is a powerful framework for #dataapps in #python. It would be really nice if it was easy to use Ipyvizzu with Panel.

As a first step I created an example of how this can be done. See https://discourse.holoviz.org/t/animated-charts-and-story-telling-with-ipyvizzu/3622 for the details.

![works-with-ipyvizzu](https://user-images.githubusercontent.com/42288570/164978875-0e98a5b9-6144-4bef-bdb0-6affd5343ff5.gif)

I've made a small tweet about it here https://twitter.com/MarcSkovMadsen/status/1518219138266804224?s=20&t=qKrkT52SeEvRLp74fHpE6g. I've shared it on LinkedIn here https://www.linkedin.com/posts/marcskovmadsen_dataapp-python-dataapp-activity-6923988516120985600-qJ_C?utm_source=linkedin_share&utm_medium=member_desktop_web.

To make it easy would probably either include some documentation on the ipyvizzu side and/ or a custom Panel pane that users can wrap the Ipyvizzu chart in to get it rendered.

This issue is mostly for info at the current state such that your community knows it can be done.

**Comment by MarcSkovMadsen** [comment]
One feedback is that I would have expected Ipyvizzu to be either an Ipywidget or have a `_repr_html_` method. Then Panel would have been able to render/ display it out of the box. Using `display_javascript` method makes it a bit different than other components for the notebook that we normally wrap. Its not a problem though.

**Comment by veghdev** [comment]
@MarcSkovMadsen Hi, we have added _repr_html_() method to Chart in ipyvizzu 0.10.0.
So I've created a simple [demo with Panel](https://github.com/vizzuhq/ipyvizzu/blob/main/docs/examples/environments/panel.md) and I've added Panel and this example to our supported [environments](https://github.com/vizzuhq/ipyvizzu#tools-support).

If you have any suggestion, please feel free to edit it and send us a PR.
