### ISSUE TITLE
Add `conda` install option for `ipyvizzu`

### ISSUE THREAD

**Issue by sugatoray** [vizzuhq/ipyvizzu#186]
A conda install option could be very helpful. Adding `ipyvizzu` to conda-forge channel will be ideal.

Note: I have started working on this already in the following PR.

- https://github.com/conda-forge/staged-recipes/pull/19838

Once merged you will be able to install the library with:

```sh
conda install -c conda-forge ipyvizzu
```

**Comment by sugatoray** [comment]
cc: @veghdev

**Comment by veghdev** [comment]
@sugatoray Thanks for your effort, that's really cool :)
