### ISSUE TITLE
Add `jsonschema` to requirements.txt

### ISSUE THREAD

**Issue by sugatoray** [vizzuhq/ipyvizzu#187]
Currently, `jsonschema` is not listed in `requirements.txt`, although it gets called when you import `ipyvizzu`. It is available in dev-requirements. But when you try installing ipyvizzu from source, and run `import ipyvizzu`, it results in failure owing to missing `jsonschema` module (`ModuleNotFoundError`)

```sh
import: 'ipyvizzu'
    import ipyvizzu
  lib/python3.10/site-packages/ipyvizzu/__init__.py", line 3, in <module>
    from .chart import Chart
  lib/python3.10/site-packages/ipyvizzu/chart.py", line 10, in <module>
    from ipyvizzu.animation import Animation, Snapshot, AnimationMerger
  lib/python3.10/site-packages/ipyvizzu/animation.py", line 8, in <module>
    import jsonschema  # type: ignore
ModuleNotFoundError: No module named 'jsonschema'
```

## Note:

I spotted this while adding the library to conda-forge in the following PR.

- https://github.com/conda-forge/staged-recipes/pull/19838

**Comment by veghdev** [comment]
@sugatoray Thanks for your help, we released your fix in [0.12.1](https://github.com/vizzuhq/ipyvizzu/releases/tag/0.12.1)
