### ISSUE TITLE
add Spark dataframe array support (Data class)

### ISSUE THREAD

**Issue by petervidos** [vizzuhq/ipyvizzu#194]
Enable users to use Spark dataframe next to the currently available pandas dataframe.
More info: https://spark.apache.org/docs/3.1.1/api/python/reference/api/pyspark.sql.DataFrame.html

**Comment by mike576** [comment]
I would implement this the following way.
In many cases, the spark df contains a large amount of data, e.g. 1 billion rows, but as with other visualization tools, I would random sample the data if it is too large. Let's say, 50 rows of pandas df is still optimal for vizzu. If the spark df is larger than 50k rows, then I would random sample the spark data frame to have roughly 50k rows, then I would call pysparkdf.toPandas() function to convert it to pandas df.

```
max_rows_for_vizzu=50000 
rownum=sparkdf.count()
pandasdf=None
if rownum > max_rows_for_vizzu:
    pandasdf=sparkdf.sample(fraction=max_rows_for_vizzu/rownum, seed=42).toPandas()
else:
    pandasdf=sparkdf.toPandas()

# handle pandas df with vizzu...

```

**Comment by veghdev** [comment]
It may be in a separate module and depend on sparkdf as an "extras".

**Comment by veghdev** [comment]
@mike576 I started to implement a `pyspark  -> vizzu`  data converter module (without pandas), and I have a problem with the sampling. It returns different rows on different machines even using the same seed value (on the same machine it returns the same for every run).
I dont really know pyspark, could you please help what can cause this kind of difference?
(pyspark version is the same)
