### ISSUE TITLE
Typo in repository About sidebar text

### ISSUE THREAD

**Issue by BioGeek** [vizzuhq/ipyvizzu#195]
The [About sidebar text of this repository](https://github.com/vizzuhq/ipyvizzu#:~:text=About-,Build%20animated%20charts%20in%20Jupyter%20Notebook%20and%20in%20many%20other%20environments%20with%20a%20simple%20Python%20synthax,-.):

> Build animated charts in Jupyter Notebook and in many other environments with a simple Python synthax.

contains a typo: `synthax` needs to be [`syntax`](https://www.merriam-webster.com/dictionary/syntax).

**Comment by simzer** [comment]
Thanks, fixed.
