### ISSUE TITLE
make os independent development environment

### ISSUE THREAD

**Issue by parkerkain-8451** [vizzuhq/ipyvizzu#197]
Currently - Mac users cannot run any of the `make` commands for the repo - which forces repo maintainers to reformat code written by Mac users. 

This applies to both `ipyvizzu` and `ipyvizzu-story`

**Comment by veghdev** [comment]
maybe use poe and poetry instead of makefile

- [ ] support different python versions (python>=3.6)
  - [ ] 3.6
  - [ ] 3.7
  - [ ] 3.8
  - [ ] 3.9
  - [ ] 3.10
  - [ ] 3.11
- [ ] support different os
  - [ ] ubuntu22 lts
  - [ ] win10,11
  - [ ] osx
