### ISSUE TITLE
Tutorial Notebook for setting Chart Styles

### ISSUE THREAD

**Issue by parkerkain-8451** [vizzuhq/ipyvizzu#201]
Please let me know if I'm misunderstanding some of how this works! 

My current understanding is the documentation for updating Styles for charts is present in the JS Vizzu library, but not super clear for the `ipyvizzu`. 

My PR #200 adds a small Style tweak, but I think a full tutorial on Style properties and how to change them could help a lot, especially to explain a little of how python users can leverage the js documentation to customize plots. If this seems valuable, I would be happy to take a shot of making such a notebook. If so - feel free to tag me as the Assignee, but if not or if this documentation already exists feel free to close 👍

**Comment by veghdev** [comment]
@parkerkain-8451 We would like to make more easily available the configuration and styling options in our documentation in the near future.

What we thought about:
- link the [Style](https://lib.vizzuhq.com/latest/reference/modules/vizzu.Styles.html) and [Config](https://lib.vizzuhq.com/latest/reference/modules/vizzu.Config.html) chapters of vizzu-lib in the Style and Config classes in the ipyvizzu code reference and in the tutorial.
- make more examples

If you have any additional suggestions or would like to participate in these developments, your help is very welcome.

**Comment by veghdev** [comment]
We released our new documentation site, we add cross references (in code reference [Config](https://ipyvizzu.vizzuhq.com/latest/reference/ipyvizzu/animation/#ipyvizzu.animation.Config), [Style](https://ipyvizzu.vizzuhq.com/latest/reference/ipyvizzu/animation/#ipyvizzu.animation.Style), etc) to vizzu-lib for available options, and create a [Style tutorial chapter](https://ipyvizzu.vizzuhq.com/latest/tutorial/style/) with styling properties.
