### ISSUE TITLE
question: does ipyvizzu work in PyCharm

### ISSUE THREAD

**Issue by petervidos** [vizzuhq/ipyvizzu#209]
PyCharm is a popular Python IDE, it would be great to see if ipyvizzu and ipyvizzu-story work in it.
Pic: Kaggle State of Data Science and Machine Learning Survey 2022
![image](https://user-images.githubusercontent.com/10341970/210221622-6f4dde01-06fa-44a3-a624-af2291a40b1e.png)

**Comment by veghdev** [comment]
@petervidos 
PyCharm Pro version is needed to run jupyter notebooks.
In the pro version both ipyvizzu and ipyvizzu-story works, but only with the repr_html/display_html(play) methods.
ipyvizzu's scroll_into_view feature does not work.
ipyvizzu-story's full screen button does not work.

**Comment by veghdev** [comment]
I will update the environments chapters with PyCharm.
