### ISSUE TITLE
add numpy array support (Data class)

### ISSUE THREAD

**Issue by petervidos** [vizzuhq/ipyvizzu#211]
Suggested by @ucontacti.
Reach out to him for more specific suggestions if needed

**Comment by veghdev** [comment]
It may be in a separate module and depend on numpy as an "extra".

**Comment by veghdev** [comment]
@ucontacti In this [Pull Request](https://github.com/vizzuhq/ipyvizzu/pull/255), I have created an implementation that supports adding up to 2-dimensional numpy arrays. I would like to gather your thoughts on whether there might be a need to extend this support to 3 or more dimensions. Additionally, do you have any suggestions on how we could effectively map/convert arrays in such cases?
