### ISSUE TITLE
question: how to show percentage on label in a 100% stack plot

### ISSUE THREAD

**Issue by MagicalKyaru** [vizzuhq/ipyvizzu#216]
Hello ! 

I am new to this lib and I love it. I might have missed it, but I was wondering if it is possible for the labels to show the percentage instead of the count value when going from a normal stack column to a 100% stack column for example. This would really help when presenting.

Thanks a lot !

**Comment by simzer** [comment]
Hi,
Which label are you referring to? The labels of the axis or the labels of the markers (using the label channel)?
You can change the marker labels with a workaround, if you calculate an additional data series containing the percentage values you want to show on the markers: https://jsfiddle.net/simzer/qzuk6Lwc/8/
