### ISSUE TITLE
documentation: create data conversion examples

### ISSUE THREAD

**Issue by veghdev** [vizzuhq/ipyvizzu#232]
create examples how to load data from excel, google sheet, sql etc. to pandas

- [x] excel
- [x] google sheet
- [x] sql (SQLite, MySQL, PostgreSQL, Microsoft SQL Server)
- [ ] etc? if you're missing something else that would be useful

**Comment by Shivraj-Nakum** [comment]
which file to add these examples ?

**Comment by veghdev** [comment]
Hi, thanks for the question.
I think it could be good inside the Tutorial - Data - Ading data - Using pandas DataFrame chapter.
https://github.com/vizzuhq/ipyvizzu/blob/main/docs/tutorial/data.md

For example:
```
### Using `pandas` DataFrame
...
#### Loading from Excel
...
```

**Comment by veghdev** [comment]
and it would also be useful to create a test for it to detect if the doc example breaks.

**Comment by schaumb** [comment]
done
