### ISSUE TITLE
question: ipyvizzu is not showing plot output in jupyter lab

### ISSUE THREAD

**Issue by dove88** [vizzuhq/ipyvizzu#242]
Hi,
I need your help, i am getting blank output in the Jupiter lab and notebook with ipyvizzu

Please check the error that i am getting

![ipyvizzu.PNG](https://user-images.githubusercontent.com/85496354/232739848-f57d826c-004c-4c27-a3a8-7f3a8be7c075.PNG)

**Comment by veghdev** [comment]
The problem is not related to ipyvizzu.
