### ISSUE TITLE
Website example charts - possible data issue

### ISSUE THREAD

**Issue by dannylee8** [vizzuhq/ipyvizzu#296]
Hi team,
I came across two data issues while running the sample charts.  

Chart 1: Distribute - Dot Plot 1 [link](https://ipyvizzu.vizzuhq.com/latest/examples/analytical_operations/distribute/newmeasure_dotplot_1/)

Copying sample code to Jupyter notebook and running it will fail when trying to read the data from https://ipyvizzu.vizzuhq.com/0.17/assets/data/IMDB_data_data_1974_1990.csv.  Appears extra commas are shifting CSV file columns over by 1 (expecting 4 columns, but a few rows have 5, due to extra comma in the Title name)

Chart 2: Sum - Column to Waterfall [link](https://ipyvizzu.vizzuhq.com/latest/examples/analytical_operations/sum/column_to_waterfall/)
When I follow the setup instructions and copy the code to Jupyter notebook, there appears to be extra data causing the chart to look cluttered.

----
Example on webpage:
![image](https://github.com/vizzuhq/ipyvizzu/assets/51715345/abcfaba9-22a0-412c-a447-cab52506d24c)

---- 
Code in JN: 
![image](https://github.com/vizzuhq/ipyvizzu/assets/51715345/8b84b988-6ec0-427e-90d0-cd6dee14f55b)

---- 

Thanks for working on this!

**Comment by veghdev** [comment]
@dannylee8 Thanks for reportin, fixed in #298
