### ISSUE TITLE
Refactor ipyvizzu.Chart.animate() to handle animoptions

### ISSUE THREAD

**Issue by veghdev** [vizzuhq/ipyvizzu#35]
ipyvizzu.Chart.animate() can not handle animoptions (like delay, duration etc.).

The JS API accepts the following arguments:
animate({ data, config, style }, animoptions)
animate(config, animoptions)
animate({ data, config, style })
animate(config)

ipyvizzu's behavior do not need to be the same like the JS API, so it can be pythonic, but the functions have to work.
(animoptions is a js object like a python dict, or in js api it can be a single string if only want to change the duration so '500ms' instead of {duration: '500ms'})

I think possible solutions in ipyvizzu are:

I.
kwargs only be animoptions
style, data and config only be Style, Data, Config classes in args
(it is a further problem with this, Style(None) needs to work to reset previous style modifications, but now it is working only in kwargs style=None)

II.
create az animOptions class, and handle it differently in _merge_animations()

III.
any other idea

**Comment by nyirog** [comment]
> I.

I like the idea to have a minimal set of kwargs options so only animoptions could be assed as keyword argument.

> (it is a further problem with this, Style(None) needs to work to reset previous style modifications, but now it is working only in kwargs style=None)

I thought that both `Style(None)` and `style=None` will end up in `{"style": null}`. Does the extra parameters beside `Style(...)` and `style=...` causes the problem?

> II.

We could move the merge rule into the `Animation` classes so every animation could merge into each other (or raise an error). This would be very flexible but not so easy to reason about.

@veghdev, could yout give some example (maybe from the vizzu documentation) where we have this problem?

**Comment by veghdev** [comment]
@nyirog Thanks, based on your comment, I will stay with option I. and I'll write the pull request for this issue in the next days.

The problem with style reset:
- We want to send {"style": null} to the JS API
(there is an example in the 5th animation: https://vizzuhq.github.io/ipyvizzu/examples/palette_font.html)
- Now, we can do it in that way: chart.animate(style=None) (as a kwarg)
- But now we can not initialize Style class with None: Style(None) raise TypeError: 'NoneType' object is not iterable

**Comment by veghdev** [comment]
Sorry, I do not know, @simzer Is there other animation which can be null?

**Comment by simzer** [comment]
@nyirog No, config and data cannot be null (at least for now), but animOption can.

This is the API declaration file for JS in TypeScript format: 
https://github.com/vizzuhq/vizzu-lib/blob/main/src/apps/weblib/js-api/vizzu.d.ts

**Comment by simzer** [comment]
Also, on the JS API animate can accept a snapshot parameter instead of { data, config, style }, which is a chart state previously saved by a chart.store() call, basically a pointer to an object on the webassembly heap.
