### ISSUE TITLE
pypi release with github action

### ISSUE THREAD

**Issue by nyirog** [vizzuhq/ipyvizzu#62]
I just tried `Upload Python Package` github action to upload new release to `pipy.org`.

Should we use this action for `ipyvizzu`?

/cc @simzer , @veghdev

**Comment by veghdev** [comment]
I think the same. It can be useful, but with a manual trigger only.

**Comment by simzer** [comment]
or... we could create a development branch, and merge it to the main only if the changes should be released?

**Comment by nyirog** [comment]
The gihub release triggers the action.

If you release the project on github then the action will build an sdist and upload it to pypi

**Comment by nyirog** [comment]
Unfortunately I do not have the right to create new token on pypi or add secret to the project.

@simzer could you create a new api token on pypi and add it to the project secrets as `PYPI_API_TOKEN`?

**Comment by simzer** [comment]
@veghdev could you please create and add the token, thx!

**Comment by veghdev** [comment]
done
