### ISSUE TITLE
preset charts 

### ISSUE THREAD

**Issue by simzer** [vizzuhq/ipyvizzu#66]
Chart presets for commonly used chart types with same API as mathplotlib.
https://matplotlib.org/stable/plot_types/index.html

**Comment by simzer** [comment]
see JS API:
https://vizzu-lib-main.storage.googleapis.com/lib/vizzu.d.ts (Vizzu.presets)
https://vizzu-lib-main.storage.googleapis.com/lib/presets.d.ts

**Comment by veghdev** [comment]
implemented in [0.12.0](https://github.com/vizzuhq/ipyvizzu/releases/tag/0.12.0)
